services: docker
jobs:
  include:
  - stage: mac integration tests
    os: osx
    osx_image: xcode10.2
    language: node_js
    node_js: '12'
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - stage: linux + windows integration tests and all platforms build
    os: linux
    language: node_js
    node_js: '12'
    services: docker
    deploy:
      skip_cleanup: true
      provider: releases
      api_key:
        secure: D3H4h11A5pgO9L2GQ66VEMRsWmgOQ7Nu71OF/F+pRyoUFTynjS84a4BJRFEU6NYC6kCZxOfH1EHgUzpKvvo+JkiNQNvMe8HFIKqiLlNZikwZukuZfU9Pj9ORRC3LXfC4pUkritBjNmOOivLZK6hopXGALgiGvMXIOpLtK/7HcJSyRNZLmLEAjksVcZNI4XKuD0OcHLcNPZ9b00Dkx9gF7Z5AKAsvn0qXHVS1yhjA9jDuyhwawCxorCoR1r87EU+hrXWIwsbyrG+0ecy90zs8wK4qg1PTnp/06uXeoWdRt+qeNU8DUqP5sxRUzp76ZxnL1UtedSMhbypkxDnSOBOlD3M3pMzBZGEhF3ADic51MlsiITljuRzoaup/h466MYgfTDZto0b+A6SsG4YU+LzwKzzx1DiO9ZAkvnsj4i0x9GvHDVYs3Z92AJ9pfGPp2QySHlxm9FtFdmvfUP/VqOMDh2A29qUJ8gcLprBRVAEB/Jo/r05/Fp6E0ZLONaLeNlZzXoDKbq+L1s9EsFu8e0cR3ABwZOXEDvb4qcpqYjrfl0R/7wneehBVilYFBPBhj4EdOrwdc1Qv5rw6XpnsdczPvYiqThKMTt186kmzZaGeHhzHInxG8bJazCBYKSNqxyrpGsAYbCG6sLYJ8ljrhdQaFgXicL/9+hsUI2Jk7FQAVKY=
      on:
        repo: knowclip/knowclip
        tags: true
      draft: false
      file_glob: true
      file:
        - dist/Knowclip_*
cache:
  directories:
  - node_modules
  - "$HOME/.cache/yarn"
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
script:
- |	
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    yarn && yarn integration && ./docker/docker_run.sh --linux --win --mac
  else	
    yarn && yarn integration
  fi
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
- rm -rf node_modules/.cache/terser-webpack-plugin
- rm -rf node_modules/.cache/babel-loader
branches:
  only:
  - master
  - /v\d+\.\d+.\d+(-.+)?/

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &