services: docker
jobs:
  include:
  - os: osx
    osx_image: xcode10.2
    language: node_js
    node_js: '12'
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - os: linux
    services: docker
    language: generic
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
script:
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    ./docker/docker_run.sh --linux --win
  else
    yarn dist --mac
  fi
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
deploy:
  provider: releases
  api_key:
    secure: OhuDDhUttZxsm5FGfVli3ZsFIibrWCArC0wCNIkIJuZnR/sz6zqpufi41MqGVWJ1PXVlzOx0hpGrWeTy4Zhtf3xo7R+lQidlV3EQOo4OZ3KTdr3tlQ+uQYVNkG+4yNp+N2/MBAlMc9BJ3SNG/euxs1dXWdPbVO6IJJrAt6d0Ky1rR2EHH/cZSyEgLBgg2eLoQOBpfoYBC3BzLLW1ivZoK80gtxxhVqPwhmuFgmAFrA1CQIb75Y9O40qSfzOt2e0Fln6trPzwnGhnmZAY1rkj0ybRQhhaFn2K9nTUYppNplFq7Et9Fm/dGAlc6BzvXyEiJ/xtVtQmxAocPx/bCm1gMy36eOoXKHwEDIuNBFeKskalnM34yTDZenExbW9DWt0qboUMbE01z7cYBayNkR4D3WXQlSR+031UGcI3ZfHNyHv/jWgfD4Qp3QXyRYGzyjKdsIoR5CG00x2uqAphPSjZ1uMKhsnI4PaGPwKHX/8gw495SmvMVT7utPs0YSaUunQRF9gh5v23NiKP1y8nmEKCF0OFz2GwiSUHpXRTBsDbDnmv0MU77K0NKKU2ZBJC+XkdSmzt/cfR/VRGLTnlgWjc7AKEeKw26z8n40Nuj1Gtw2aVtxN6n3BftYoP3TgWcqHGdCH3glbskuZQgWZffG/eWj/8F1MNgxIT/mNXIizj1Mo=
  file:
    - dist/knowclip_0.5.0_amd64.deb
    - dist/Knowclip-0.5.0.AppImage
    - dist/Knowclip-0.5.0-mac.zip
    - dist/Knowclip-0.5.0.dmg
    - dist/Knowclip 0.5.0.exe
  draft: true
  on:
    repo: knowclip/knowclip
branches:
  only:
  - master
