image: Visual Studio 2017

platform:
  - x64
  - x86

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12 x64
  - yarn

build_script:
  - set REACT_APP_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%
  - yarn dist:appveyor

test: off

test_script:
  - set REACT_APP_SPECTRON=True
  - yarn integration:appveyor
  - set REACT_APP_SPECTRON=False