image: Visual Studio 2017

platform:
  - x64
  - x86

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12 x64
  - yarn

build_script:
  - cmd: set REACT_APP_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%
  - yarn dist:appveyor --win --ia32 --x64

test_script:
  - cmd: set REACT_APP_SPECTRON=True
  # only testing this one for now to save time and
  # copyFixtures is broken on Windows, so tests
  # relying on it won't work here
  - yarn integration:appveyor -t "shared project"
  - cmd: set REACT_APP_SPECTRON=False

skip_commits:
  files:
    - homepage/*
    - docker/*
    - travis.yml
    - '*.md'
