image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12 x64
  - yarn

build_script:
  - cmd: set REACT_APP_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%
  - yarn dist:appveyor -p onTag --win

skip_commits:
  files:
    - homepage/*
    - docker/*
    - travis.yml
    - '*.md'

branches:
  only:
    - master
    - /v\d+\.\d+.\d+(-.+)?/