image: Visual Studio 2017

platform:
  - x64
  - x86

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12 x64
  - yarn

build_script:
  - cmd: set REACT_APP_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%
  - cmd: set REACT_APP_BUILD_NUMBER
  - cmd: set APPVEYOR_BUILD_NUMBER
  - yarn dist:appveyor

test_script:
  - cmd: set REACT_APP_SPECTRON=True
  - cmd set REACT_APP_SPECTRON
  - yarn integration:appveyor -t "shared project"
  - cmd: set REACT_APP_SPECTRON=False