name: Linux Node CI

on: [push]

jobs:
  linux_build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.8.1]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install and test
      run: |
        yarn install --frozen-lockfile
        yarn format --list-different
        yarn lint
        yarn tsc
        yarn test
        (cd homepage && yarn install --frozen-lockfile)
    - name: integration tests
      run: |
        export DISPLAY=':99.0'
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        yarn integration
    - name: build
      run: yarn dist --linux
      env:
        CI: false
    - name: Upload build artifacts
      if: "!startsWith(github.ref, 'refs/tags/')"
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/Knowclip_*
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: dist/Knowclip_*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

